### ISSUE TITLE
Edit version on existing JIRA throws class cast exception

### ISSUE THREAD

**Issue by nreeb** [jenkinsci/jira-steps-plugin#25]
When I try to update an existing JIRA with a new fix version I get a class cast exception.

java.lang.ClassCastException: org.thoughtslive.jenkins.plugins.jira.api.input.FieldsInput.fixVersions expects class [Lorg.thoughtslive.jenkins.plugins.jira.api.Version; but received class org.thoughtslive.jenkins.plugins.jira.api.Version

My code is below. the found version is a variable of type version.

def jiraIssue = [fields: [fixVersions: foundVersion]]
echo jiraIssue.toString()
response = jiraEditIssue idOrKey: result.data.id, issue: jiraIssue, site: "JIRA"

**Comment by nrayapati** [comment]
fixVersion(s) is list of versions, where in you were sending just one of them. 

Changing it to a list should solve the issue. 

```groovy
def jiraIssue = [fields: [fixVersions: [foundVersion]]]
```
Few examples related to fixVersion can be found at https://jenkinsci.github.io/jira-steps-plugin/common_usages.html just in case if you need more help.

**Comment by nreeb** [comment]
That gets rid of the class cast exception. Now I get

java.lang.NullPointerException
	at org.thoughtslive.jenkins.plugins.jira.steps.EditIssueStep$Execution.verifyInput(EditIssueStep.java:123)
	at org.thoughtslive.jenkins.plugins.jira.steps.EditIssueStep$Execution.run(EditIssueStep.java:76)
	at org.thoughtslive.jenkins.plugins.jira.steps.EditIssueStep$Execution.run(EditIssueStep.java:61)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:49)
	at hudson.security.ACL.impersonate(ACL.java:213)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:46)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


Ill look at the examples, but I have been trying a million things and keep getting this null pointer.

**Comment by nrayapati** [comment]
For me it looks like you are running on old version(1.0.0), try to upgrade to the latest version to avoid from the few bugs, and also the examples are based on the master code.

From the exception, issuetype is missing or the id is missing in there from [1].

[1] https://github.com/jenkinsci/jira-steps-plugin/blob/jira-steps-1.0.0/src/main/java/org/thoughtslive/jenkins/plugins/jira/steps/EditIssueStep.java#L123

**Comment by nreeb** [comment]
Thanks! Once I updated the plugin I was good to go.
